hydra:
    run:
        dir: ./results/predict/${now:%Y-%m-%d}/${now:%H-%M-%S}
gpu: 0
load:
        model: 'results/train/augmentation_1/16-43-25/model.pt'
model:
        mean: 0.000703781869206
        std: 0.011581798172958
        input_layers: 3
        layers: 32
        residual: True
        kernal_size: 5
        activation_function: 'ReLU'
        pooling_method: 'max'
        normalization: True
target:
        path: 'results/train/augmentation_1/16-43-25/data_new.pkl'
        cell: [[37.79453756, 0, 0],
               [0, 37.79453756, 0],
               [0, 0, 37.79453756]]
        mesh: [80, 80, 80]
